### ISSUE TITLE
why i can't import python package

### ISSUE THREAD

**Issue by qqt-code** [yuelinan/DARE#3]
in Faith-DARE/ogbg/main_mi.py line 12 ,from dataset import PolymerRegDataset,i can not import PolymerRegDataset.I want to know if I installed the wrong package. Could you please provide me with the version of this package?

**Comment by yuelinan** [comment]
Hi, I have uploaded the dataset.py.
Besides, Faith-DARE is an extended version of our journal and is still under review.

**Comment by qqt-code** [comment]
ok,thanks for your help and good luck for you.
